name: Build Server arm64

on:
  workflow_dispatch:

env:
  MODULE: server
  PLATFORM: linux_arm64
  DOCKER_TAG: onlyoffice-builder
  BUILD_PATH: ./out
  PACKAGE_REPO: https://github.com/ONLYOFFICE/document-server-package.git

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: Build project
      run: |
        mkdir -p $BUILD_PATH
        docker build --build-arg BRANCH=${{ github.ref_name }} \
                     --build-arg MODULE=${{ env.MODULE }} \
                     --build-arg PLATFORM=${{ env.PLATFORM }} \
                     --tag ${{ env.DOCKER_TAG }} .
        docker run -v $PWD/${{ env.BUILD_PATH }}:/build_tools/${{ env.BUILD_PATH }} ${{ env.DOCKER_TAG }}

    - name: Package deb
      run: |
        cd ..
        git clone ${{ env.PACKAGE_REPO }}
        cd document-server-package
        git checkout -f ${{ github.ref_name }}
        npm install -g pkg
        sudo apt-get update
        sudo apt-get -y install build-essential debhelper
        VERSION=$(echo ${{ github.ref_name }} | sed 's/^tags\///; s/^v//')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        PRODUCT_VERSION=$VERSION BUILD_NUMBER='1' make deb
        mkdir -p $GITHUB_WORKSPACE/deb/
        cp deb/onlyoffice-documentserver_$VERSION-1_arm64.deb $GITHUB_WORKSPACE/deb/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: onlyoffice-documentserver_${{ env.VERSION }}-1
        path: deb/onlyoffice-documentserver_${{ env.VERSION }}-1_arm64.deb
